name: shltr_flutter
description: SHLTR flutter app
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  sentry_flutter: ^7.16.1
  bloc_concurrency: ^0.2.3
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  firebase_core: ^2.25.1
  firebase_messaging: ^14.7.12
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_branch_sdk: ^7.0.2
  flutter_cache_manager: ^3.3.1
  http: ^1.2.0
  latlong2: ^0.9.0
  modal_progress_hud_nsn: ^0.5.1
  open_filex: ^4.3.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  streaming_shared_preferences: ^2.0.0
  uni_links: ^0.5.1
  upgrader: ^9.0.0
  url_launcher: ^6.2.4
  logging: ^1.2.0
  flutter_typeahead: ^4.0.0
  my24_flutter_core:
#    path: ../my24_flutter_core
    git:
      url: https://github.com/My24Service/my24_flutter_core.git
  my24_flutter_equipment:
#    path: ../my24_flutter_equipment
    git:
      url: https://github.com/My24Service/my24_flutter_equipment.git
  my24_flutter_member_models:
    #    path: ../my24_flutter_member_models
    git:
      url: https://github.com/My24Service/my24_flutter_member_models.git
  my24_flutter_orders:
#        path: ../my24_flutter_orders
    git:
      url: https://github.com/My24Service/my24_flutter_orders.git


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.2.0
  network_image_mock: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # Our translation resources
  assets:
    - assets/icon/icon.png
    - assets/bg1.jpg
    - assets/bg2.jpg
    - assets/bg3.jpg
    - assets/bg4.jpg
    - resources/langs/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"